### ISSUE TITLE
Failed setup, will retry: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by dlehrbaum** [runDMCA/home-assistant-mazda#6]
Upon initialization, I receive the following error message in the integrations. This is a new installation. Version information is included at the bottom of this post.

> Failed setup, will retry: 'NoneType' object is not subscriptable

Debug logging reveals the following additional detail:

> Logger: custom_components.mazda
> Source: custom_components/mazda/__init__.py:159
> integration: Mazda Connected Services
> First occurred: 8:13:12 PM (10 occurrences)
> Last logged: 8:16:55 PM
> 
> Unknown error occurred during Mazda update request: 'NoneType' object is not subscriptable
> Traceback (most recent call last):
>   File "/config/custom_components/mazda/__init__.py", line 159, in async_update_data
>     vehicle["status"] = await with_timeout(
>                         ^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/mazda/__init__.py", line 57, in with_timeout
>     return await task
>            ^^^^^^^^^^
>   File "/config/custom_components/mazda/pymazda/client.py", line 99, in get_vehicle_status
>     alert_info = vehicle_status_response.get("alertInfos")[0]
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
> TypeError: 'NoneType' object is not subscriptable

**Version Information:**
- Integration: 1.0
- Core: 2024.10.2
- Supervisor: 2024.10.0

**Comment by dlehrbaum** [comment]
This can be closed. It is likely that I was attempting to connect too soon after activating Mazda Connect Services. 12 hours later, everything is up and running without error. Thanks for a great HA integration!
